using Microsoft.ML.OnnxRuntime;
using Microsoft.ML.OnnxRuntime.Tensors;
using NBA.Inference;

namespace NBA.Inference.Tests;

public class OnnxModelPipelineTests
{
    private static string FixturePath => Path.Combine(AppContext.BaseDirectory, "Assets", "add-one.onnx");

    // The fixture model computes output = input + 1 for a [1, 4] float tensor - see
    // tests/NBA.Inference.Tests/Assets/ (generated by a small Python script, not committed as source-of-truth
    // logic, just a deterministic fixture for exercising the pipeline's wiring).
    [Fact]
    public void Run_PreprocessRunPostprocess_ProducesExpectedOutputShape()
    {
        using var pipeline = new OnnxModelPipeline<float[], float[]>(
            FixturePath,
            preprocess: input =>
            {
                var tensor = new DenseTensor<float>(input, [1, 4]);
                return [NamedOnnxValue.CreateFromTensor("input", tensor)];
            },
            postprocess: results => results.First(r => r.Name == "output").AsTensor<float>().ToArray());

        var result = pipeline.Run([1f, 2f, 3f, 4f]);

        Assert.Equal([2f, 3f, 4f, 5f], result.Output);
    }

    [Fact]
    public void Run_MeasuresNonNegativeLatency()
    {
        using var pipeline = new OnnxModelPipeline<float[], float[]>(
            FixturePath,
            preprocess: input => [NamedOnnxValue.CreateFromTensor("input", new DenseTensor<float>(input, [1, 4]))],
            postprocess: results => results.First(r => r.Name == "output").AsTensor<float>().ToArray());

        var result = pipeline.Run([0f, 0f, 0f, 0f]);

        Assert.True(result.Latency >= TimeSpan.Zero);
    }

    [Fact]
    public void Run_ReportsPlatformProvider_OnThisMachine()
    {
        using var pipeline = new OnnxModelPipeline<float[], float[]>(
            FixturePath,
            preprocess: input => [NamedOnnxValue.CreateFromTensor("input", new DenseTensor<float>(input, [1, 4]))],
            postprocess: results => results.First(r => r.Name == "output").AsTensor<float>().ToArray());

        // macOS has CoreML EP support built into the base ONNX Runtime package, so it's expected to report
        // CoreMl here rather than falling back to Cpu. Any other platform without a GPU EP branch (e.g. Linux)
        // falls back to Cpu.
        var expected = OperatingSystem.IsMacOS() ? ExecutionProviderKind.CoreMl : ExecutionProviderKind.Cpu;
        Assert.Equal(expected, pipeline.Provider);
    }
}
